
[[pages]]
path = "pages/broad_mkt.py"
name = "Broad Market"

[[pages]]
path = "pages/sector.py"
name = "Sector Analysis"

[[pages]]
path = "streamlit_app.py"
name = "Stock Analysis"

[[pages]]
path = "pages/glossary.py"
name =  "Glossary"